[target.wasm32-unknown-emscripten]
rustflags = [
  "-Clink-arg=--no-entry",
  "-Clink-arg=-sSTANDALONE_WASM=0",
  "-Clink-arg=-sFILESYSTEM=0",
]

[env]
CFLAGS_wasm32_unknown_emscripten = "-fPIC"
CXXFLAGS_wasm32_unknown_emscripten = "-fPIC"
